// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post.proto

package via.dk.elearn.protobuf;

public interface NewPostRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NewPostRequest)
    com.google.protobuf.MessageOrBuilder {
}
