// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post.proto

package via.dk.elearn.protobuf;

public interface PostModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PostModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string body = 2;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 2;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
