// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post.proto

package via.dk.elearn.protobuf;

public final class Post {
  private Post() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewPostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewPostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostLookupModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostLookupModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\npost.proto\"\020\n\016NewPostRequest\"\036\n\017PostLo" +
      "okupModel\022\013\n\003url\030\001 \001(\t\"4\n\tPostModel\022\n\n\002i" +
      "d\030\001 \001(\003\022\014\n\004body\030\002 \001(\t\022\r\n\005title\030\003 \001(\t2c\n\013" +
      "PostService\022\'\n\007GetPost\022\020.PostLookupModel" +
      "\032\n.PostModel\022+\n\nGetAllPost\022\017.NewPostRequ" +
      "est\032\n.PostModel0\001B\032\n\026via.dk.elearn.proto" +
      "bufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NewPostRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NewPostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewPostRequest_descriptor,
        new java.lang.String[] { });
    internal_static_PostLookupModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PostLookupModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostLookupModel_descriptor,
        new java.lang.String[] { "Url", });
    internal_static_PostModel_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PostModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostModel_descriptor,
        new java.lang.String[] { "Id", "Body", "Title", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
