// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package via.dk.elearn.protobuf;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLookupModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserLookupModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Username_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Username_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"\216\001\n\tUserModel\022\n\n\002id\030\001 \001(\003\022\020" +
      "\n\010username\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\020\n\010passw" +
      "ord\030\004 \001(\t\022\021\n\tfirstName\030\005 \001(\t\022\020\n\010lastName" +
      "\030\006 \001(\t\022\017\n\007country\030\007 \001(\t\022\014\n\004role\030\010 \001(\t\"\035\n" +
      "\017UserLookupModel\022\n\n\002id\030\001 \001(\003\"\034\n\010Username" +
      "\022\020\n\010userName\030\001 \001(\t2\216\001\n\004User\022(\n\rGetUserBy" +
      "Name\022\t.Username\032\n.UserModel0\001\022-\n\rCreateN" +
      "ewUser\022\020.UserLookupModel\032\n.UserModel\022-\n\013" +
      "GetUserByID\022\020.UserLookupModel\032\n.UserMode" +
      "l0\001B\'\n\026via.dk.elearn.protobufP\001\252\002\nElearn" +
      "Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserModel_descriptor,
        new java.lang.String[] { "Id", "Username", "Email", "Password", "FirstName", "LastName", "Country", "Role", });
    internal_static_UserLookupModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserLookupModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserLookupModel_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Username_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Username_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Username_descriptor,
        new java.lang.String[] { "UserName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
