// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package via.dk.elearn.protobuf;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLookupModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserLookupModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"s\n\tUserModel\022\020\n\010username\030\001 " +
      "\001(\t\022\020\n\010password\030\002 \001(\t\022\021\n\tfirstName\030\003 \001(\t" +
      "\022\020\n\010lastName\030\004 \001(\t\022\017\n\007country\030\005 \001(\t\022\014\n\004r" +
      "ole\030\006 \001(\t\"\035\n\017UserLookupModel\022\n\n\002id\030\001 \001(\003" +
      "2d\n\004User\022-\n\013GetUserById\022\020.UserLookupMode" +
      "l\032\n.UserModel0\001\022-\n\rCreateNewUser\022\020.UserL" +
      "ookupModel\032\n.UserModelB\'\n\026via.dk.elearn." +
      "protobufP\001\252\002\nElearnGrpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserModel_descriptor,
        new java.lang.String[] { "Username", "Password", "FirstName", "LastName", "Country", "Role", });
    internal_static_UserLookupModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserLookupModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserLookupModel_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
